### ISSUE TITLE
Datagrid text overlaps across columns

### ISSUE THREAD

**Issue by davazlan** [blazority/support#100]
Description
The text contained in datagrid columns overlaps between them

Code
This is an example of a table:
`<Datagrid TRowData="UPVAdapterTask" Items="Tasks" Selection="SelectionMode.None" Compact="false" Fixed="FixedMode.All" style="max-height: 600px">
                <DatagridColumn Title="Id" TRowData="UPVAdapterTask" Field="c => c.UPVAdapterTaskId.ToString()" CanSort="true" CanFilter="true" CanResize="false"/>
                <DatagridColumn Title="Model" TRowData="UPVAdapterTask" Field="c => tasksService.GetUPVModel(c.UPVModelId) != null ? tasksService.GetUPVModel(c.UPVModelId).Name : string.Empty" CanSort="true" CanFilter="true" />
                <DatagridColumn Title="Type" TRowData="UPVAdapterTask" Field="c => c.Type.ToString()" CanSort="true" CanFilter="true" />
                <DatagridColumn Title="Status" TRowData="UPVAdapterTask" Field="c => c.Status.ToString()" CanSort="true" CanFilter="true" CanResize="false"/>
                <DatagridColumn Title="Started On" TRowData="UPVAdapterTask" Field="c => c.StartedOn.ToString(dateFormatSpecifier, currentCulture)" CanSort="true" CanFilter="false" CanHide="true" CanResize="false" />
                <DatagridColumn Title="Finished On" TRowData="UPVAdapterTask" Field="c => c.FinishedOn.ToString(dateFormatSpecifier, currentCulture)" CanSort="true" CanFilter="false" CanHide="true" CanResize="false" />
                <DatagridColumn Title="Time Converting" TRowData="UPVAdapterTask" Field="c => c.ExtractionDuration.ToString()" CanHide="false" CanSort="true" CanFilter="true">
                    <ChildContent>
                        @(context.ExtractionDuration.Hours)h @(context.ExtractionDuration.Minutes)m
                    </ChildContent>
                </DatagridColumn>
                <DatagridColumn Title="SourceFiles" TRowData="UPVAdapterTask" Field="c => string.Join(Environment.NewLine, c.InputFiles)" CanSort="false" CanFilter="true" CanHide="true" CanResize="false" />
                <DatagridColumn Title="OutputFile" TRowData="UPVAdapterTask" Field="c => c.OutputFile" CanHide="false" CanSort="true" CanFilter="true" CanResize="false" />
                <DatagridColumn Title="Project" TRowData="UPVAdapterTask" Field="c => c.Project != null ? c.Project.ToString() : string.Empty" CanSort="true" CanFilter="true" CanResize="false" />
                <DatagridRowActions TRowData="UPVAdapterTask" CanShow="@CanShowActions">
                    <DatagridRowActionItem>
                        <Icon Shape="times" Status="Status.Danger"></Icon>
                        <Button Variant="Danger" Flat="true" Small="true" type="button" OnClick="() => DeleteAdapter(context)">Delete</Button>
                    </DatagridRowActionItem>
                    <DatagridRowActionItem>
                        <Icon Shape="eraser" Status="Status.Warning"></Icon>
                        <Button Variant="Warning" Flat="true" Small="true" type="button" OnClick="() => ResetAdapter(context)">Reset Status</Button>
                    </DatagridRowActionItem>
                </DatagridRowActions>
                <DatagridFooter TRowData="UPVAdapterTask">
                    <DatagridPagination @ref="Paginator" TRowData="UPVAdapterTask" PageSize="5" PageSizes="new int[] { 1, 3, 5, 10, 20, 30 }" PageSizeLabel="Tasks per page">
                        @(Paginator.Pager.StartIndex + 1) - @(Paginator.Pager.EndIndex + 1) of @(Paginator.Pager.ItemCount) tasks
                    </DatagridPagination>
                </DatagridFooter>
            </Datagrid>`

**Environment**
 - Blazority Version 0.12.3
 - .NET Core Version 6.0
 - Browser Brave (chrome)

** Screenshots**
![image](https://user-images.githubusercontent.com/41060273/177990079-57a635a5-ef7d-440a-8439-773c37d5372b.png)

**Comment by davazlan** [comment]
BTW, this doesn't happen with Blazority Version 0.12.2

**Comment by thg87** [comment]
Hi everybody,

i have the same problem. The datagrid has enough space but the datagrid columns are overlapping. 

- Blazority Version: 1.0.3
- .Net Core 6
- Chrome

**Comment by karan-kang** [comment]
This is happening because the text does not have any spacing, you can resolve this by wrapping the content of your column in another span with following CSS class:

.break-all { word-break: all }

https://www.w3schools.com/cssref/tryit.php?filename=trycss3_word-break
