### ISSUE TITLE
Support row refresh when using server side datagrid

### ISSUE THREAD

**Issue by nicolajb23** [blazority/support#104]
**Feature Type**
[ ] Clarity Port
[ X ] Enhancement

**Description**
When using a server side Datagrid we have live notifications that can update the value for a single cell in the table.
Currently we have to refresh the entire datagrid which the user is complaining about because of the spinner and if several notifications quickly the list becomes unusable from their perspective.

Can we add a way to just refresh a row?

**Comment by karan-kang** [comment]
@nicolajb23 Refreshing one row can have implications on the sorting, and filtering as well. How are you planning to handle that?
