### ISSUE TITLE
Combobox: Enter key is not replacing selected item in single selection mode

### ISSUE THREAD

**Issue by PR33T0** [blazority/support#108]
**Describe the bug**
When you have focus on a combox and you open the popup via the spacebar, the selected item does not become visible.

**To Reproduce**
1. Go to '[https://blazority.com/combobox](https://blazority.com/combobox)'
2. Focus on the Combobox.
3. Hit the spacebar, 
4. Use arrows of the keyboard to select an item with the enter key.
5. See error

**Environment**
 - Blazority Version [1.0.0]
 - Browser [chrome]

**Comment by karan-kang** [comment]
@PR33T0 I was unable to reproduce this with our examples on these pages:
https://blazority.com/combobox/standalone
https://blazority.com/combobox/form

Can you please post what error are you seeing?

**Comment by PR33T0** [comment]
There is no error message, With see the error i mean that you don't select the item. If have the functionality to open the combobox with space key, i think you also want the item to get selected if you hit the enter key. If you delete the space before hitting enter the selection of the item is working.

**Comment by karan-kang** [comment]
thanks @PR33T0, I was able to reproduce and find the root cause. We will be fixing this in upcoming release.
