### ISSUE TITLE
Tree View Checkbox - Ancestor nodes are not evaluating properly

### ISSUE THREAD

**Issue by pufpufpuf** [blazority/support#114]
**Describe the bug**
The checkboxes of parent - parent - ... are not evaluated correctly.

**To Reproduce**

**First case:**
![image](https://user-images.githubusercontent.com/16465655/197182967-af641178-2654-4e8a-9ae4-4bdf9cf84aa9.png)

Uncheck everything.

Click on Alex User
![image](https://user-images.githubusercontent.com/16465655/197183079-ab8870c4-5b8a-470f-88b7-0cc4cc65f893.png)

Parent Node is not updated correctly.

**2nd case:**

Check Alex, Gerardo, Ebony.
Everything seems fine
![image](https://user-images.githubusercontent.com/16465655/197183307-c9a2d9b8-2045-4ef7-9eab-c788b32abdc1.png)

Then uncheck all of them.
![image](https://user-images.githubusercontent.com/16465655/197183418-54d13e89-4356-4aaa-abcd-d17f8721fa91.png)

Parent - Parent Node Alex is not updated accordingly.

**3th case:**
if working with disabled checkboxes (just to visualize some items)
the parents aren't showed correctly as well.
![image](https://user-images.githubusercontent.com/16465655/197184118-b390c495-d8f4-4b9c-a979-7274d0ffa9f9.png)

**Environment**
 - Blazority Version [1.02]
 - .NET Core Version [6.0]
 - Browser [chrome]

**Comment by karan-kang** [comment]
Fixed in v1.0.4
