### ISSUE TITLE
Missing source maps for dependencies from Nuget package

### ISSUE THREAD

**Issue by BigWinston** [blazority/support#119]
**Describe the bug**
Probably a dumb question/issue, but here goes...  After following the Get Started instructions and reloading my new Blazor project I see the following errors in the console:

DevTools failed to load source map: Could not load content for https://localhost:7140/_content/Blazority/lib/webcomponents/custom-elements/custom-elements.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load source map: Could not load content for https://localhost:7140/_content/Blazority/lib/clr/ui/clr-ui.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

DevTools failed to load source map: Could not load content for https://localhost:7140/_content/Blazority/lib/clr/icons/clr-icons.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

In Chome dev tools, I have verified the sources all exist in the _content paths in the folders listed in the stylesheet links.

**To Reproduce**
1. Create a new Blazor (server) project using .NET wizard
2. Follow Get Started Blazority instructions
3. Start development server
4. View Inspect console to see the warnings

**Environment**
 - Blazority Version : 1.0.3
 - .NET Core Version : 6
 - Browser : Chrome

**Comment by karan-kang** [comment]
@BigWinston  We will fix this in upcoming version, thanks for reporting.
