### ISSUE TITLE
Datagrid pagination: no way to set the current page

### ISSUE THREAD

**Issue by nicolajb23** [blazority/support#121]
**Describe the bug**
We are using a blend of server side and client side datagrids with paging, and capturing the page information in the URL for reload purposes.
There is no way to set the current page on reload, or get the current page (on change) for client side.

**Environment**
 - Blazority Version 1.0.4
 - .NET Core Version 6
 - Browser Chrome

**Comment by karan-kang** [comment]
New events and methods provided on DatagridPagination component:

![image](https://user-images.githubusercontent.com/1234394/213964212-3cd05e86-ca94-4dcc-88fd-646eb73164dc.png)
