### ISSUE TITLE
Icon: add support for warning badge

### ISSUE THREAD

**Issue by nicolajb23** [blazority/support#122]
**Feature Type**
[ x ] Clarity Port
[ x ] Enhancement

**Description**
Clarity cds-icon now supports a "warning" badge, add support

**Comment by karan-kang** [comment]
to be released

**Comment by karan-kang** [comment]
![image](https://user-images.githubusercontent.com/1234394/213964412-19a75ff6-2a04-4e6a-a12a-8d8cd2e4a10c.png)
