### ISSUE TITLE
Combobox: Activate FilteredItemsAsync when dropdown opens

### ISSUE THREAD

**Issue by nicolajb23** [blazority/support#124]
**Describe the bug**
When using the FilteredItemsAsync and clicking the dropdown arrow (with or without text) no loading is done and no results shown.

**To Reproduce**
1. Go to https://blazority.com/combobox/features
2. Select 'Async Loading'
3. Click the arrow on the 'Asynchronous load on filter' combobox

**Environment**
 - Blazority Version 1.0.4
 - .NET Core Version 6
 - Browser Chrome

**Comment by PR33T0** [comment]
Hi,

If you start typing it will start loading.


Kind regards,

Simon DEPREZ
Project Engineer Software

M: +32 470 882 725<tel:+32470882725>
________________________________
From: Nicola ***@***.***>
Sent: Friday, December 16, 2022 9:31:57 PM
To: blazority/support ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [blazority/support] Combobox: Activate FilteredItemsAsync when dropdown opens (Issue #124)


Describe the bug
When using the FilteredItemsAsync and clicking the dropdown arrow (with or without text) no loading is done and no results shown.

To Reproduce
Steps to reproduce the behavior:

  1.  Go to https://blazority.com/combobox/features<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fblazority.com%2Fcombobox%2Ffeatures&data=05%7C01%7Cs.deprez%40scottautomation.be%7C2fb733f5142c42e9ae5c08dadfa494d8%7C8f5f2f5cf644447cb6eb9b43d9d21dfd%7C0%7C0%7C638068195210012215%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3YbiflzIxC5CIRyIBSMqRvzHGCrXpHYyP102ynu66JU%3D&reserved=0>
  2.  Select 'Async Loading'
  3.  Click the arrow on the 'Asynchronous load on filter' combobox
  4.  See error

Environment

  *   Blazority Version 1.0.4
  *   .NET Core Version 6
  *   Browser Chrome

**Comment by karan-kang** [comment]
Resolved in v1.1.0, to be released
