### ISSUE TITLE
No way to set initial page number for Data Grid before rendering

### ISSUE THREAD

**Issue by GurpreetRaju** [blazority/support#131]
The issue related to https://github.com/blazority/support/issues/121. We are facing following issues:
- Currently there is no way to set page number before the data grid is rendered (Not using server side pagination - query by).
- When using Server side pagination (QueryBy), even thought the pagination result has the correct skip count, the datagrid footer shows Page number 1, however the rows are loaded from correct page. The page number in footer is not in sync with the grid rows. This happens only when the page number is other than 1, when data grid is rendered for first time.

**Environment**
 - Blazority Version 1.1.0
 - .NET Core Version 6
 - Browser Chrome

**Comment by karan-kang** [comment]
Fixed with v1.1.1

- Added new property "PageNum" on DatagridPagination to set the initial page number for both client side and server side mode
- Server side now correctly updates the page number based on the Skip property of PagedResult<T>
