### ISSUE TITLE
Hamburger menu not shown using Blazor Server

### ISSUE THREAD

**Issue by V3nn3tj3** [blazority/support#135]
**Describe the bug**
When using a sidenav on a blazor server application the hamburger menu is only shown on the first session connected. For other sessions the menu is hidden on small screens but the hamburger menu is not shown.

**To Reproduce**
1. add header and verticalnav (with nav=primary) to maincomponent in a blazor server application
2. start blazor app
3. browse to blazor app with "browser 1" and resize to see hamburger menu
4. browse to blazor app with "browser 2" and resize, menu is hidden but hamburger menu is not shown

**Environment**
 - Blazority Version 1.1.1
 - .NET Core 6
 - Chrome, Firefox, Edge, ...
 
 **Remark**
Looks like the check to show hamburger menu is based on a static list of navigationlevels. An event is used to refresh the header with hamburger menu when the nav is added, only when no navigationlevels exist.
On blazor server this static list contains all navigationlevels for all sessions connected. When the first browser navigates to the app, static list is empty and hamburger menu is added by event. For the second browser navigates to the app, the list already contains one nav -> no event is thrown and hamburger menu is missing for the second session/browser.

**Comment by karan-kang** [comment]
This was fixed in v2.0.0
