### ISSUE TITLE
Datagrid: Column hiding does not work if column is hidden during initialization

### ISSUE THREAD

**Issue by peer-kkang** [blazority/support#138]
**To Reproduce**
1) Create a Datagrid (local or server) with 4 Columns (Name, Age, City, Country)
2) Set CanHide=true for Age and City columns
3) Set Hidden=true for Age column
4) Run app, Age column will be hidden as expected
5) Click the Toggle for Show/Hide column in datagrid footer
6) Name, City, Country column are shown with checked checkbox state as expected, clicking on these toggles the column
7) Age column is shown with unchecked checkbox state as expected, **clicking on this does not toggle the Age column and the checkbox just flickers**

**Environment**
 - Blazority Version: 1.1.0
 - .NET Core Version: 6.0
 - Browser: Chrome/Edge Chromium

**Comment by karan-kang** [comment]
Fixed in 1.2.0, to be released

**Comment by karan-kang** [comment]
Fixed in 2.0.0, released today
