### ISSUE TITLE
Incorrectly displaying error messages for DatePicker/DateTimePicker

### ISSUE THREAD

**Issue by DDaarcon** [blazority/support#140]
**Describe the bug**
Error messages for DateTimePicker (this is the one I use) and DatePicker (see on documentation website) are inconsistent with respect to other form fields (icon in a different place) and overall don't appear correctly - part of the message is overlapping with the icon.
Only on the "Compact" form layout message and icon don't overlap BUT on this layout icon is placed on top of the next field.

**To Reproduce**
Just look at documentation website
![image](https://github.com/blazority/support/assets/39386052/18202a4c-3b6a-455a-a217-d9d957567c5a)
![image](https://github.com/blazority/support/assets/39386052/d320bfbf-9e27-4e7b-ad01-d4150a84b993)

**Environment**
 - Blazority Version [1.1.1]

**Comment by karan-kang** [comment]
Fixed in v1.2.0, to be released

**Comment by karan-kang** [comment]
Fixed in v2.0.0, released today
