### ISSUE TITLE
Upgrade to DotNet 8

### ISSUE THREAD

**Issue by MarceloRangel74** [blazority/support#141]
**Feature Type**
[ ] Clarity Port
[x] Enhancement

**Description**
Please check the possibility of updating the project to .NET 8. I tested Blazority in a Blazor Web App project, and the icons stop being displayed when navigating between pages. I suspect there may be other inconsistencies. 

This library has become really, really good, and it would be a shame not to update it.

**Comment by karan-kang** [comment]
Resolved via v2.0.0 release, please check the getting started guide as the theme usage/switching between light and dark theme has changed, for more information see Changelog: https://github.com/blazority/support/blob/2.0.0/CHANGELOG.md
