### ISSUE TITLE
ViewData collection changed

### ISSUE THREAD

**Issue by venjirai** [blazority/support#143]
Hello,
I want to aggregate field values in currently displayed datagrid columns (ViewData) by summing up decimal values to get the total.
To achieve that I need to be notified when ViewData changes (filter changes, item changes, page changes, ....)
Is there a already built in way to achieve that? I having trouble implementing it myself since ViewData is an IReadOnlyCollection

**Comment by karan-kang** [comment]
@venjirai You should be able to do this by using the server driven model of Blazority Datagrid. The "QueryBy" callback is triggered any time filter, page, sorting is changed. You can perform the total as needed in this call to modify your result set.

See the code block here for more information:
https://blazority.com/datagrid/server-side

**Comment by karan-kang** [comment]
Feel free to re-open this if you have further questions.

You can also submit a demo of your current datagrid by forking the REPL:
https://replit.com/@Karankang007/Blazority-REPL
