### ISSUE TITLE
Datagrid 

### ISSUE THREAD

**Issue by wheric** [blazority/support#2]
**Description**

Datagrid SelectedItem cannot be unselected by setting the bound property to null. 

**To Reproduce**

1. Bind Blazority Datagrid SelectedItem to a property.
2. After populating data and selecting the row the SelectedItem property is set properly.
3. If you set the SelectedItem property to NULL on a Button click event the SelectedItem property appears to be called in an infinite loop from then on and the page is no longer responsive. 

**Expected behavior**

Row should be deselected.

**Actual behavior**

Row is not deselected and page becomes unresponsive. 

**Environment**
 - OS: Windows 10
 - Browser: Chrome
 - Blazority Version: 0.5.0
 - .NET Core Version : 5

Project with modified Index.razor showing behavior. 
[TestBlazority.zip](https://github.com/blazority/support/files/6018106/TestBlazority.zip)

**Comment by karan-kang** [comment]
Fixed in v0.6.0
