### ISSUE TITLE
Datepicker popup overlaps window border

### ISSUE THREAD

**Issue by gritsenko** [blazority/support#24]
**Feature Type**
[ ] Clarity Port
[x] Enhancement

**Description**
If the datepicker is located too close to bottom window border it's cut by window border and I have to add margin to bottom of the page to be able to scroll down, to see whole calendar. Also popup doesn't scrolling with page.
![image](https://user-images.githubusercontent.com/2227312/133047247-66a849c0-3e8b-4a8b-a0a2-4e2b22e831e2.png)

- So it will be useful at least to have option to choose **popup direction** for popup calendar. 
- And will be perfect if popup will be able to check available space and automatically change direction. As a reference, it's implemented Radzen controls.

p.s. thanks for your job! it's really clean implementation of design system in blazor!

**Comment by karan-kang** [comment]
Thanks for the feedback and workaround suggestion, long term we have a plan to support auto placement for overlay elements like DatePicker, Dropdown, Signposts, Tooltip, etc.

**Comment by karan-kang** [comment]
@gritsenko For the short term, I have added Position parameter to DatePicker, DateRangePicker, DateTimePicker, and TimePicker controls in upcoming v0.9.1

**Comment by gritsenko** [comment]
Thank you very much, @karan-kang !
