### ISSUE TITLE
Header search bar styling documentation

### ISSUE THREAD

**Issue by curt-w** [blazority/support#29]
**Feature Type**
[ ] Clarity Port
[X ] Enhancement

**Description**
I'm having extreme difficulty templating in a search input within the header. I have the following code within the application header region.

`<Header><BrandingRegion><Branding Icon="code">Header</Branding></BrandingRegion><SearchRegion><Form Model="@model" Layout="FormLayout.Compact"><Text @bind-Value="model.SearchValue"></Text></Form></SearchRegion><Settings><NavItem Icon="cog"></NavItem></Settings></Header>`

I'm not sure how to apply styling to the components so they appear within the header correctly. I've attempted to suppress / manipulate the standard form / input CSS that is being applied (i.e. for formatting in the content area) without any success.

Would you be able to improve documentation, or at least help me out in getting this templated up? I've referenced the application layout section to get this far. Is there a general pattern to follow for overriding styling of components I leverage? I've attempted applying ::deep to some CSS styles, i.e. "::deep label { width: 0!important; }" within my header's CSS.

Another question if possible - it seems the text / number inputs must be used in conjunction with the Form component; is it possible to utilize these controls without an actual form / model binding? Perhaps, bind the text box to a property on the component? A lot of my formatting issues I think might be coming from the styling associated with the form.

**Comment by karan-kang** [comment]
Hi @curt-w, thanks for your feedback, I have updated the docs for Search functionality in Header component based on Clarity design. 

![image](https://user-images.githubusercontent.com/1234394/135014983-c501c96f-d4c8-4d9c-9d61-319b0a62de95.png)


```

<!--As a standalone search region-->
<Header ColorOption="6">
    <BrandingRegion>
        <Branding Icon="file">Note App</Branding>
    </BrandingRegion>
    <SearchRegion>
        <EditForm class="search" role="search" Model="@searchOneModel">
            <label for="search_input">
                <input id="search_input" type="text" @bind="@searchOneModel.Text" placeholder="Search for keywords..." />
            </label>
        </EditForm>
    </SearchRegion>
</Header>

<!--As a search region next to Navigation Items-->
<Header ColorOption="6">
    <BrandingRegion>
        <Branding Icon="file">Note App</Branding>
    </BrandingRegion>
    <NavigationRegion>
        <HeaderNav>
            <NavItem>Dashboard</NavItem>
            <NavItem>Analysis</NavItem>
        </HeaderNav>
    </NavigationRegion>
    <SearchRegion>
        <EditForm class="search" role="search" Model="@searchTwoModel">
            <label for="search_input">
                <input id="search_input" type="text" @bind="@searchTwoModel.Text" placeholder="Search for keywords..." />
            </label>
        </EditForm>
    </SearchRegion>
</Header>

<!--As a toggle in Header Actions-->
<Header ColorOption="6">
    <BrandingRegion>
        <Branding Icon="file">Note App</Branding>
    </BrandingRegion>
    <NavigationRegion>
        <HeaderNav>
            <NavItem>Dashboard</NavItem>
            <NavItem>Analysis</NavItem>
        </HeaderNav>
    </NavigationRegion>

    <Actions>
        @if (searchThreeModel.Open)
        {
            <EditForm class="search-box" role="search" Model="@searchThreeModel">
                <input id="search_input" type="text" autofocus @bind="@searchThreeModel.Text" placeholder="Search for keywords..." />
            </EditForm>
        }

        <NavItem Icon="search" @onclick="() => { searchThreeModel.Open = !searchThreeModel.Open; }"></NavItem>
        <Dropdown Position="Position.BottomRight">
            <DropdownTrigger>
                <HeaderDropdownButton Icon="user"></HeaderDropdownButton>
            </DropdownTrigger>
            <DropdownMenu>
                <DropdownItem>Preferences</DropdownItem>
                <DropdownDivider></DropdownDivider>
                <DropdownItem>About</DropdownItem>
                <DropdownItem>Help</DropdownItem>
            </DropdownMenu>
        </Dropdown>
    </Actions>
</Header>

@code {

    public DemoSearchModel searchOneModel = new DemoSearchModel(true);
    public DemoSearchModel searchTwoModel = new DemoSearchModel(true);
    public DemoSearchModel searchThreeModel = new DemoSearchModel(false);

    public class DemoSearchModel
    {
        public string Text { get; set; }
        public bool Open { get; set; }

        public DemoSearchModel(bool open)
        {
            Open = open;
        }
    }
} 
```

**Comment by karan-kang** [comment]
Marking as Closed, please feel free to reopen if you have any follow up queries.
