### ISSUE TITLE
feature: collapsible sidenav groups

### ISSUE THREAD

**Issue by leetheman** [blazority/support#34]
Hello, is it possible to have a property to set the default state for SiedNav collapsible groups, I have a very large sidenav and I don't want all the options to be open.

If possible, it would be great if there were two types of collapsible - normal style (each group can be collapsed /expended indepdenently) or accordian (expanding a group will close all others)

Happy to assist in the dev of this if that's an option?

**Comment by karan-kang** [comment]
Thanks for your feedback @leetheman, I will add this is upcoming release
