### ISSUE TITLE
Column selection popup cutoff and cannot be closed

### ISSUE THREAD

**Issue by nicolajb23** [blazority/support#36]
**Describe the bug**
Using a data grid with columns that can be hidden.  The column selection popup is cutoff at the top of the data grid and will not close.
![image](https://user-images.githubusercontent.com/71723448/141688830-4f9a4e1f-8549-4d0d-a02a-b087998eeea6.png)

**To Reproduce**
1. Create data grid with CanHide="true" for several columns
2. Have a collection with very few rows (i.e. mine has 1 at the moment)
3. Click the column selector button

**Environment**
 - Blazority Version 0.9.4

**Comment by karan-kang** [comment]
Fixed in v0.9.5
