### ISSUE TITLE
Datagrid icons not properly shown

### ISSUE THREAD

**Issue by Mikhail-Belanov** [blazority/support#37]
**Blazority versions 0.9.5 and 0.9.4**

Icons applied to columns headers are not shown or shown in huge size.
Navigation buttons in the DatagridPagination are not shown or shown in huge size
**To Reproduce**
1. Create any Datagrid with rows.
2. Publish to IIS or IIS Express
3. Icons errors in headers are shows immediately and  in DatagridPagination are show after fill the data.

**Environment**
 .NET Core 5
Blazor Server Project type. 
 Browser - Chrome, FireFox (don't matter)

**The reason and workaround**
clricons.min.js have to be downloaded but clr-icons.min.js are present instead. The lack of clricons.min.js is reported in Visual Studio 2019 debug output. Similar error is shown there too: customelements.min.js not found.
Workaround: I have copied all of clr-icons.* to clricons.* and custom-elements.min.* to customelements.min.* in the same folders
and made that folders published in the Visual Studio project.

**Comment by karan-kang** [comment]
I tried investigating this using the default ASP.NET Core 5 template but did not run into this issue.

I will do some more digging on this and get back to you over the weekend.

**Comment by karan-kang** [comment]
@Mikhail-Belanov Me and my team are unable to reproduce this issue.
please feel to reopen with more steps to reproduce if you are still running into this issue
