### ISSUE TITLE
Datagrid:expandable row has an extra col

### ISSUE THREAD

**Issue by PamyAnnPatrick** [blazority/support#4]
**Description**

Expandable rows has an extra col in the data grid when the table layout is fixed.

**Environment**

OS: Windows 10
Browse: Edge
Blazority Version: 0.6.2
.NET Core Version: 3.1

**Comment by karan-kang** [comment]
Fixed in 0.6.2

**Comment by karan-kang** [comment]
Reopening due to regression found in 0.6.3
