### ISSUE TITLE
Blazority - cannot set total items

### ISSUE THREAD

**Issue by sebastianroibu** [blazority/support#5]
How can I set total count of items if the pagination is done in backend and the items set to the datagrid context are only for 1 page ?

Example code:

> <Datagrid Items="AllContracts">
        <DatagridColumn Title="Id" TRowData="ContractModel" Field="c => c.Id" CanSort="true" />
        <DatagridColumn Title="Reference" TRowData="ContractModel" Field="c => c.Reference" CanSort="true" />
        <DatagridFooter TRowData="ContractModel">
            <DatagridPagination @ref="Paginator" TRowData="ContractModel" PageSize="15" PageSizes="new int[] { 15, 30, 50 }"
                                PageSizeLabel="Contracts per page">
                @(Paginator.Pager.StartIndex + 1) - @(Paginator.Pager.EndIndex + 1) of @TotalCount contracts
            </DatagridPagination>
        </DatagridFooter>
    </Datagrid>

**Comment by karan-kang** [comment]
@sebastianroibu At the moment, clarity datagrid does not support server side pagination/filtering/sorting, this feature is a work in progress, and we aim to complete this by v0.8.0. In the client side mode, datagrid automatically determines the item count based on the length of bound Items collection.

**Comment by karan-kang** [comment]
Blazority v0.8.0 supports server driven pagination, sorting, and filtering. This requirement is now fulfilled by that feature, see demo and usage instructions at [](https://blazority.com/datagrid/server-side)
