### ISSUE TITLE
feature: File Input

### ISSUE THREAD

**Issue by karan-kang** [blazority/support#56]
**Feature Type**
[x ] Clarity Port
[ ] Enhancement

(https://clarity.design/core-components/file/)

**Comment by PR33T0** [comment]
When can we expect this feature?

**Comment by karan-kang** [comment]
https://blazority/file

![image](https://user-images.githubusercontent.com/1234394/213967054-b43f30cc-f530-419a-9918-7413b7b438b3.png)
