### ISSUE TITLE
Datagrid row actions slow

### ISSUE THREAD

**Issue by davazlan** [blazority/support#66]
### Discussed in https://github.com/blazority/support/discussions/62

<div type='discussions-op-text'>

<sup>Originally posted by **davazlan** February 10, 2022</sup>
The datagrid row actions pop up quite slowly. What could be impacting the performance?
My implementation looks like this currently:
```
<DatagridRowActions TRowData="Model" CanShow="@CanShowActions">
                    <DatagridRowActionItem>
                        <Icon Shape="note" Status="Status.Info"></Icon>
                        <Button Variant="Info" Flat="true" Small="true" type="button" OnClick="() => EditModel(context)">Edit</Button>
                    </DatagridRowActionItem>
                    <DatagridRowActionItem>
                        <Icon Shape="eraser" Status="Status.Danger"></Icon>
                        <Button Variant="Danger" Flat="true" Small="true" type="button" OnClick="() => DeleteModel(context)">Delete</Button>
                    </DatagridRowActionItem>
                </DatagridRowActions>
```

Could it be the button making them render slowly?</div>

**Comment by karan-kang** [comment]
@davazlan Couple of questions for investigation:

- Blazor hosting model (Server or Web Assembly)?
- Blazority version?
- .NET version?
- Number of rows?
- Is the datagrid using server-side mode?

**Comment by davazlan** [comment]
Hi @karan-kang, thanks for coming back to me:
* Server
* latest (0.10.0)
* 5.0
* < 20
* No server-side

**Comment by davazlan** [comment]
Hi @karan-kang, it must have been something on my side because I haven't changed anything and now the lag is gone.
