### ISSUE TITLE
Datagrid: 'select all' checkbox remains selected when user uncheck individual rows

### ISSUE THREAD

**Issue by PamyAnnPatrick** [blazority/support#7]
**Describe the bug**
Data grid 'select all' checkbox remains selected when user uncheck individual rows

**To Reproduce**
1. Go to https://blazority.com/datagrid/multi-selection
2. Click on select all checkbox in the data grid.
3. Uncheck checkbox in individual rows.
(Select all checkbox still remains selected.)

**Environment**
 - OS: Windows 10
 - Browser: Edge
 - Blazority Version 0.7.2
 - .NET 5

**Comment by karan-kang** [comment]
Reopening this bug: The current fix when selection changes are made using UI, but does not work if Selection changes are made programmatically (especially in multi-selection mode)

**Comment by karan-kang** [comment]
Datagrid does not support detecting changes (add/remove/clear) on bounded items.

If the selected items need to be changed programmatically, then modifications must be made on DatagridInstance.SelectionItems property where DatagridInstance can be retrieved using @ref keyword. This is now clarified in the documentation for 0.7.5

**Comment by karan-kang** [comment]
Reopening as this is still happening in 0.7.7

**Comment by karan-kang** [comment]
Fixed in v0.8.0
