### ISSUE TITLE
Support for .net 6 

### ISSUE THREAD

**Issue by karan-kang** [blazority/support#81]
> Originally requested by [nicolajb23](https://github.com/nicolajb23) on Apr 6, 2022

**Feature Type**
[ ] Clarity Port
[ x ] Enhancement

**Description**
Could Blazority be updated to support .NET 6

**Comment by curt-w** [comment]
FYI, I am utilizing Blazority under .NET 6.0 without issue.

**Comment by PR33T0** [comment]
> FYI, I am utilizing Blazority under .NET 6.0 without issue.

Me to

**Comment by karan-kang** [comment]
Thanks @curt-w for @PR33T0 for feedback, we will still like to go ahead with providing official support for .NET 6 to see if there are any further packaging or bundling improvements in the library.
