### ISSUE TITLE
Timepicker: Ability to use up or down button continuously in rolling mode

### ISSUE THREAD

**Issue by nicolajb23** [blazority/support#88]
**Feature Type**
[ ] Clarity Port
[ x ] Enhancement

**Description**
Currently at 0 hours or 0 minutes you cannot click Up buttons, similarly at 23 hours or 59 minutes you cannot click Down buttons.

Make the buttons work continuously - i.e. 0 hours -> 23 hours on Up and 23 -> 0 on Down

**Comment by karan-kang** [comment]
Releasing in v0.12.0
