### ISSUE TITLE
Multi combobox: More control for selected items

### ISSUE THREAD

**Issue by nicolajb23** [blazority/support#91]
**Feature Type**
[ ] Clarity Port
[ x ] Enhancement

**Description**
I would like to be able to prevent a user from removing a selected item using the x in the pill, backspace or clicking on the item in the list.
Also it would be valuable to be able to control the hover text for the selected item pill too especially in this scenario to provide feedback as to why the item cannot be removed.
Maybe also add a class so it could be styled differently in this scenario.

**Comment by karan-kang** [comment]
Releasing in v0.12.0
