### ISSUE TITLE
Icons are gone in V12

### ISSUE THREAD

**Issue by davazlan** [blazority/support#94]
Hi, I was very happy to see a new release so I immediately updated, rebuilt and tested. Now all the icons are gone. Are there any breaking changes I should've been aware of?

![image](https://user-images.githubusercontent.com/41060273/173287272-b8ba8172-7298-4987-88f2-7c25051d4d83.png)

**Comment by karan-kang** [comment]
@davazlan 
We are investigating this, and should be able to release a fix for this today.

**Comment by karan-kang** [comment]
Fixed with v0.12.1 (https://www.nuget.org/packages/Blazority/0.12.1).

New version: 
https://blazority.com/
https://62a7376c85fbfe48c91b152c--blazority.netlify.app
