### ISSUE TITLE
Issue w/ grouped application alerts

### ISSUE THREAD

**Issue by curt-w** [blazority/support#95]
Related to issue #84.

After updating to 0.12.1, testing issue #84, new issues identified. Issue encountered when three or more alerts are queued up, then closed.

Unrecoverable rendering issue occurs when you queue up four alerts, then close.

Please see below video - I exhibit each case (one alert, two alerts, three alerts, floor? oops four) twice in the video. You will see an odd miscount occur after queuing up three alerts and closing one; broader issues occur if four are queued and then closed.

![app_alert_issue](https://user-images.githubusercontent.com/91343878/173714829-667d5d73-9be1-44fd-bc22-16a36a33650e.gif)

Take care and keep making awesome software.

**Environment**
 - Blazority Version 0.12.1
 - .NET 6
 - Edge Chromium

**Comment by karan-kang** [comment]
@curt-w 

Can you please give this a try using the example provided on our site? I tried this with 100 different alert with random add/remove but was not able to reproduce this.

- Navigate to https://blazority.com/alerts
- Switch to **App-Level**  tab
- Try the **Multiple Alerts (App Level Only)** example

The usage for the demo code is as follows:

```
<Alerts>
    @foreach (var alert in AppAlerts)
    {
        <Alert AppLevel="true" Type="@alert.AlertType">
            <AlertItem>
                <AlertText>@alert.AlertText</AlertText>
            </AlertItem>
        </Alert>
    }
</Alerts>

@code {
    // Default list of app alerts
    public List<AlertModel> AppAlerts = new List<AlertModel> {
        new AlertModel { AlertType = AlertType.Info, AlertText = "App level closable information alert" },
        new AlertModel { AlertType = AlertType.Warning,  AlertText = "App level closable information alert" },
        new AlertModel { AlertType = AlertType.Danger, AlertText = "App level closable danger alert" }
    };

    // Called by the demo "Add Random Alert" button
    public void AddAppAlert()
    {
        AppAlerts.Add(new AlertModel
            {
                AlertType = AlertType.Info,
                AlertText = "Random alert created at " + DateTime.Now.ToString()
            });
    }

    // Called by the demo "Remove Last Alert" button
    public void RemoveLastAlert()
    {
        if (AppAlerts.Any())
        {
            AppAlerts.Remove(AppAlerts.Last());
        }
    }
}


```

**Comment by karan-kang** [comment]
Marking as closed after week of inactivity, please feel free to report another issue if this is still happening.
