### ISSUE TITLE
Datagrid: Extra whitespace when using hidden columns and fixed table layout

### ISSUE THREAD

**Issue by karan-kang** [blazority/support#97]
**Describe the bug**
![image](https://user-images.githubusercontent.com/1234394/175456883-e5e34c5d-051e-4e29-80cb-3791fcf753fe.png)

**To Reproduce**
1. Set custom css like ```table[blazority] { table-layout: fixed }```
2. Hide view columns
3. Notice the footer goes beyond the total available space

**Environment**
 - Blazority Version 0.12.2
 - .NET Core Version 0.5.0
 - Browser Edge Chromium Latest

**Comment by karan-kang** [comment]
Fixed in 0.12.3

**Comment by pufpufpuf** [comment]
@karan-kang 

Version 0.12.1

![image](https://user-images.githubusercontent.com/16465655/176448095-bb87cb13-eb24-48d6-aefe-1b7fba215d7d.png)

Version 0.12.3

![image](https://user-images.githubusercontent.com/16465655/176449977-7fcb54fd-5dfd-4df3-83ad-0e59735510b0.png)

Columns are not properly resizing? Is there a setting I should change between version 0.12.1 <> 0.12.3
